group :test do
  gem 'cucumber'
  gem 'cucumber-rails'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem "autotest-rails"
  gem "autotest-notification"
  gem "rspec"
  gem "rspec-rails"
  gem "spork"
  gem "launchy"
  gem "systemu"
  gem "mongrel", "1.2.0.pre2"
end